### ISSUE TITLE
Error in plot for analysis2

### ISSUE THREAD

**Issue by firasm** [ubco-W2022T2-data301/project-group-group15#24]
Hi @keishakwek,

While @Iadel95 and I were going through your project repository, we noticed that there was an error in one of your cells that didn't produce a plot. 

Could you please fix this so we can appropriately address your project?

![Screenshot 2023-04-20 at 1 21 35 PM](https://user-images.githubusercontent.com/2507459/233479288-be1c0ac9-30cd-455b-9300-039851a160d7.png)

**Comment by keishakwek** [comment]
Hi! My greatest apologies for the error, I just checked my work and it turns out to be a block of code I initially had to make a HexPlot but did not end up including in the final report. I did remove the DataFrame used to make the HexPlot but it seems that I forgot to remove the code - sorry about that!

I have removed the block of code as it was not intended to be there in the first place. I apologize for not checking my work more thoroughly the first time. Overall, deleting this code will not effect any other part of my analysis/report. Again, I'm very sorry for any inconvenience caused and please let me know if there is anything else that should be done. Thank you!

All the best,
Keisha

**Comment by firasm** [comment]
Okay thanks - you can close the issue one you've pushed the changes to GitHub. 

cc @Iadel95
